In [38]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\movie_dataset.csv")

In [39]:
df

index     budget                                    genres   
0         0  237000000  Action Adventure Fantasy Science Fiction  \
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
4798   4798     220000                     Action Crime Thriller   
4799   4799       9000                            Comedy Romance   
4800   4800          0             Comedy Drama Romance TV Movie   
4801   4801          0                                       NaN   
4802   4802          0                               Documentary   

                                               homepage      id   
0                           http://www.avatarmovie.com/   19995  \
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language   
0     culture clash future space war space colony so...                en  \
1     ocean drug abuse exotic island east india trad...                en   
2            spy based on novel secret agent sequel mi6                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                NaN                en   
4800  date love at first sight narration investigati...                en   
4801                                                NaN                en   
4802               obsession camcorder crush dream girl                en   

                                original_title   
0                                       Avatar  \
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  ...   
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...  \
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...   
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...   
4802  Ever since the s

In [41]:
features = ['keywords', 'cast', 'genres', 'director']
for feature in features:
    df[feature] = df[feature].fillna('')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4803 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4803 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [15]:
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
df["combined_features"] = df.apply(combined_features, axis =1)

In [16]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])
print("Count Matrix: ",count_matrix.toarray())

Count Matrix:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
print(df["combined_features"])


0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6 Dan...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799     Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800    date love at first sight narration investigati...
4801     Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802    obsession camcorder crush dream girl Drew Barr...
Name: combined_features, Length: 4803, dtype: object


In [18]:
cosine_sim = cosine_similarity(count_matrix)


In [19]:
print(cosine_sim)

[[1.         0.10540926 0.12038585 ... 0.         0.         0.        ]
 [0.10540926 1.         0.0761387  ... 0.03651484 0.         0.        ]
 [0.12038585 0.0761387  1.         ... 0.         0.11145564 0.        ]
 ...
 [0.         0.03651484 0.         ... 1.         0.         0.04264014]
 [0.         0.         0.11145564 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.04264014 0.         1.        ]]


In [29]:
movie_user_like = "House of Sand and Fog"

def get_index_from(title):
    return df[df.title == title]["index"].values[0]

movie_index = get_index_from(movie_user_like)

In [30]:
print(movie_index)

2452


In [31]:
similar_movies = list(enumerate(cosine_sim[movie_index]))


In [32]:
print(similar_movies)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.04499212706658475), (4, 0.0), (5, 0.0), (6, 0.05263157894736841), (7, 0.0), (8, 0.0), (9, 0.0468292905790847), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.04499212706658475), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.04055535528269063), (25, 0.1538967528127731), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.0), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0917662935482247), (44, 0.0), (45, 0.04499212706658475), (46, 0.042601432284230495), (47, 0.0), (48, 0.0), (49, 0.05006261743217588), (50, 0.0917662935482247), (51, 0.04335549847620599), (52, 0.04891159880445184), (53, 0.0), (54, 0.047836487323493986), (55, 0.0), (56, 0.0), (57, 0.057353933467640436), (58, 0.0), (59, 0.0), (60, 0.047836487323493986), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.04499212706658475), (65, 0.044992127066584

In [33]:
sorted_similar_movies = sorted(similar_movies, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(2452, 0.9999999999999993), (1162, 0.2503130871608794), (165, 0.2445579940222592), (593, 0.21052631578947364), (493, 0.19564639521780736), (3772, 0.1873171623163388), (1452, 0.17342199390482396), (4375, 0.1720618004029213), (189, 0.16222142113076254), (2891, 0.16222142113076254), (3295, 0.16222142113076254), (3491, 0.15789473684210523), (25, 0.1538967528127731), (776, 0.1538967528127731), (1206, 0.1538967528127731), (2161, 0.1538967528127731), (3634, 0.1538967528127731), (3701, 0.1538967528127731), (3726, 0.1538967528127731), (4290, 0.1538967528127731), (1599, 0.15018785229652765), (2141, 0.15018785229652765), (3545, 0.15018785229652765), (297, 0.14673479641335552), (310, 0.14673479641335552), (454, 0.14673479641335552), (765, 0.14673479641335552), (779, 0.14673479641335552), (871, 0.14673479641335552), (1526, 0.14673479641335552), (2024, 0.14673479641335552), (78, 0.14350946197048195), (421, 0.14350946197048195), (439, 0.14350946197048195), (762, 0.14350946197048195), (824, 0.1435094

In [34]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]

i=0
for movies in sorted_similar_movies:
    print(get_title_from_index(movies[0]))
    i = i+1;
    if i>15:
        break

House of Sand and Fog
He's Just Not That Into You
Hulk
The Dilemma
A Beautiful Mind
You Kill Me
The Walk
Blue Car
Noah
The Life Before Her Eyes
Aloft
The Wackness
Titanic
Winter's Tale
The Odd Life of Timothy Green
Quigley Down Under
