In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\Tamil_movies_dataset.csv")

In [2]:
df

MovieName   Genre  Rating              Director   
0           Mouna Guru  Action     7.7          Santha Kumar  \
1          7 Aum Arivu  Action     6.2       A.R. Murugadoss   
2     Vaagai Sooda Vaa  Comedy     8.0           A. Sarkunam   
3             Mankatha  Action     7.6         Venkat Prabhu   
4     Kanchana: Muni 2  Comedy     6.5  Lawrence Raghavendra   
..                 ...     ...     ...                   ...   
324  Dhilluku Dhuddu 2  Comedy     5.3               Rambala   
325                Dev  Action     4.8    Rajath Ravishankar   
326  Charlie Chaplin 2  Comedy     3.8    Sakthi Chidambaram   
327              Petta  Action     7.3      Karthik Subbaraj   
328           Viswasam  Action     6.7                  Siva   

                    Actor  PeopleVote  Year  Hero_Rating  movie_rating   
0               Arulnithi         746  2011            8             8  \
1                  Suriya        9479  2011            9             9   
2                   Vimal       14522  2011            8             7   
3             Ajith Kumar       12276  2011            6             8   
4    Lawrence Raghavendra        1044  2011            8             9   
..                    ...         ...   ...          ...           ...   
324             Santhanam         497  2019            7             9   
325                Karthi         724  2019            5             8   
326           Prabhu Deva         215  2019            4             7   
327           Rajinikanth        7545  2019            8             8   
328           Ajith Kumar        5907  2019            8             9   

     content_rating  
0          7.900000  
1          8.066667  
2          7.666667  
3          7.200000  
4          7.833333  
..              ...  
324        7.100000  
325        5.933333  
326        4.933333  
327        7.766667  
328        7.900000  

[329 rows x 10 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   MovieName       329 non-null    object 
 1   Genre           329 non-null    object 
 2   Rating          329 non-null    float64
 3   Director        329 non-null    object 
 4   Actor           329 non-null    object 
 5   PeopleVote      329 non-null    int64  
 6   Year            329 non-null    int64  
 7   Hero_Rating     329 non-null    int64  
 8   movie_rating    329 non-null    int64  
 9   content_rating  329 non-null    float64
dtypes: float64(2), int64(4), object(4)
memory usage: 25.8+ KB


In [6]:
features = ['PeopleVote', 'Actor', 'Genre', 'Director']
for feature in features:
    df[feature] = df[feature].fillna('')

In [7]:
print (df[feature])

0              Santha Kumar
1           A.R. Murugadoss
2               A. Sarkunam
3             Venkat Prabhu
4      Lawrence Raghavendra
               ...         
324                 Rambala
325      Rajath Ravishankar
326      Sakthi Chidambaram
327        Karthik Subbaraj
328                    Siva
Name: Director, Length: 329, dtype: object


In [9]:
def combined_features(row):
    return row['Actor']+" "+row['Genre']+" "+row['Director']
df["combined_features"] = df.apply(combined_features, axis =1)

In [10]:
print(df["combined_features"])

0                         Arulnithi Action Santha Kumar
1                         Suriya Action A.R. Murugadoss
2                              Vimal Comedy A. Sarkunam
3                      Ajith Kumar Action Venkat Prabhu
4      Lawrence Raghavendra Comedy Lawrence Raghavendra
                             ...                       
324                            Santhanam Comedy Rambala
325                    Karthi Action Rajath Ravishankar
326               Prabhu Deva Comedy Sakthi Chidambaram
327                 Rajinikanth Action Karthik Subbaraj
328                             Ajith Kumar Action Siva
Name: combined_features, Length: 329, dtype: object


In [11]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])
print("Count Matrix: ",count_matrix.toarray())

Count Matrix:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
cosine_sim = cosine_similarity(count_matrix)


In [13]:
print(cosine_sim)

[[1.         0.28867513 0.         ... 0.         0.25       0.5       ]
 [0.28867513 1.         0.         ... 0.         0.28867513 0.28867513]
 [0.         0.         1.         ... 0.25819889 0.         0.        ]
 ...
 [0.         0.         0.25819889 ... 1.         0.         0.        ]
 [0.25       0.28867513 0.         ... 0.         1.         0.25      ]
 [0.5        0.28867513 0.         ... 0.         0.25       1.        ]]


In [30]:
movie_user_like = "Ko"
def get_index_from(MovieName):
    return df[df.MovieName == MovieName]["movie_rating"].values[0]

movie_index = get_index_from(movie_user_like)

In [31]:
print(movie_index)

7


In [18]:
df.head(10)

MovieName   Genre  Rating                   Director   
0        Mouna Guru  Action     7.7               Santha Kumar  \
1       7 Aum Arivu  Action     6.2            A.R. Murugadoss   
2  Vaagai Sooda Vaa  Comedy     8.0                A. Sarkunam   
3          Mankatha  Action     7.6              Venkat Prabhu   
4  Kanchana: Muni 2  Comedy     6.5       Lawrence Raghavendra   
5  Deiva Thirumagal   Drama     8.1                 A.L. Vijay   
6            Vaanam  Action     7.2  Radha Krishna Jagarlamudi   
7                Ko  Action     7.8                 K.V. Anand   
8           Payanam  Action     7.3                Radha Mohan   
9        Yutham Sei   Crime     8.0                    Myshkin   

                  Actor  PeopleVote  Year  Hero_Rating  movie_rating   
0             Arulnithi         746  2011            8             8  \
1                Suriya        9479  2011            9             9   
2                 Vimal       14522  2011            8             7   
3           Ajith Kumar       12276  2011            6             8   
4  Lawrence Raghavendra        1044  2011            8             9   
5                Vikram       44517  2011            9             9   
6     T.R. Silambarasan        1307  2011            7             8   
7                 Jiiva        4759  2011            9             7   
8    Nagarjuna Akkineni         677  2011            6             8   
9                Cheran        1678  2011            4             9   

   content_rating                                  combined_features  
0        7.900000                      Arulnithi Action Santha Kumar  
1        8.066667                      Suriya Action A.R. Murugadoss  
2        7.666667                           Vimal Comedy A. Sarkunam  
3        7.200000                   Ajith Kumar Action Venkat Prabhu  
4        7.833333   Lawrence Raghavendra Comedy Lawrence Raghavendra  
5        8.700000                            Vikram Drama A.L. Vijay  
6        7.400000  T.R. Silambarasan Action Radha Krishna Jagarla...  
7        7.933333                            Jiiva Action K.V. Anand  
8        7.100000              Nagarjuna Akkineni Action Radha Mohan  
9        7.000000                               Cheran Crime Myshkin

In [26]:
similar_movies = list(enumerate(cosine_sim[movie_index]))


In [32]:
print(similar_movies)

[(0, 0.22360679774997896), (1, 0.25819888974716115), (2, 0.0), (3, 0.19999999999999998), (4, 0.0), (5, 0.0), (6, 0.39999999999999997), (7, 0.25819888974716115), (8, 0.9999999999999999), (9, 0.0), (10, 0.25819888974716115), (11, 0.0), (12, 0.22360679774997896), (13, 0.0), (14, 0.0), (15, 0.25819888974716115), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.22360679774997896), (22, 0.22360679774997896), (23, 0.0), (24, 0.25819888974716115), (25, 0.25819888974716115), (26, 0.22360679774997896), (27, 0.19999999999999998), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.25819888974716115), (36, 0.0), (37, 0.19999999999999998), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.25819888974716115), (46, 0.0), (47, 0.22360679774997896), (48, 0.0), (49, 0.22360679774997896), (50, 0.0), (51, 0.22360679774997896), (52, 0.25819888974716115), (53, 0.0), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.19999999999999998), (58,

In [33]:
sorted_similar_movies = sorted(similar_movies, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(8, 0.9999999999999999), (121, 0.4472135954999579), (186, 0.4472135954999579), (215, 0.4472135954999579), (222, 0.4472135954999579), (300, 0.4472135954999579), (6, 0.39999999999999997), (71, 0.39999999999999997), (98, 0.39999999999999997), (180, 0.39999999999999997), (1, 0.25819888974716115), (7, 0.25819888974716115), (10, 0.25819888974716115), (15, 0.25819888974716115), (24, 0.25819888974716115), (25, 0.25819888974716115), (35, 0.25819888974716115), (45, 0.25819888974716115), (52, 0.25819888974716115), (63, 0.25819888974716115), (83, 0.25819888974716115), (110, 0.25819888974716115), (122, 0.25819888974716115), (123, 0.25819888974716115), (126, 0.25819888974716115), (133, 0.25819888974716115), (150, 0.25819888974716115), (164, 0.25819888974716115), (165, 0.25819888974716115), (167, 0.25819888974716115), (174, 0.25819888974716115), (191, 0.25819888974716115), (192, 0.25819888974716115), (195, 0.25819888974716115), (221, 0.25819888974716115), (224, 0.25819888974716115), (225, 0.25819888

In [35]:
def get_title_from_index(index):
    return df[df.index == index]["MovieName"].values[0]

i=0
for movies in sorted_similar_movies:
    print(get_title_from_index(movies[0]))
    i = i+1;
    if i>15:
        break

Payanam
Velaikkaran
Brindavanam
Maari 2
Kaatrin Mozhi
Ayogya
Vaanam
Thani Oruvan
Oopiri
Sathriyan
7 Aum Arivu
Ko
Aadukalam
The Fly
Irandam Ulagam
Pandiya Naadu
